name: xfel
channels:
  - conda-forge
  - defaults
  - pytorch3d
dependencies:
  - pytorch==1.9.0 
  - torchvision==0.10.0 
  - cudatoolkit=10.2 
  - tensorboard
  - pytorch3d
  - pip
    - configparser 
    - mrcfile 
    - scipy 
    - matplotlib 
    - starfile 
    - setuptools==59.5.0 
    - ipykernel
